name: ServerMon 
description: "Server Monitor app to check server details"
publish_to: 'none'
version: 1.5.0

environment:
  sdk: ^3.5.3

dependencies:
  bottom_picker: ^2.8.0
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
